### ISSUE TITLE
Unable to create a folder

### ISSUE THREAD

**Issue by ghost** [muonium/core#101]
When I'm entering the name of my folder and pressing enter key, nothing happen (nothing in the db)

**Comment by Super-Baleine** [comment]
Personally I don't have this problem.

**Comment by ghost** [comment]
Informations :
--------------
POST http://127.0.0.1:8080/core/User/AddFolder
Host: 127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://127.0.0.1:8080/core/User
Content-Type: application/x-www-form-urlencoded
Content-Length: 23
Cookie: PHPSESSID=2egvrf66qfbg2t1o7pc44sbn37; lang=fr
Connection: keep-alive

folder_id=0&folder=test

Return : "error"

**Comment by Super-Baleine** [comment]
@hitoshi54 and @ayagebreel did you get this bug while testing ?

**Comment by Super-Baleine** [comment]
@Ne0blast were you on the 'interface' branch, last commit ?

**Comment by ghost** [comment]
It was commit 91cf54d098611d8c1f483c5406713a26a584fe95

**Comment by Super-Baleine** [comment]
Okay

**Comment by Super-Baleine** [comment]
Perhaps you should delete core/, clone again, and delete and next create a new database, and at last, execute the last cloud.sql located at the _interface_ branch.

**Comment by ayagebreel** [comment]
Now I created folder and it created successfully and I found it in Data Base also.

**Comment by Super-Baleine** [comment]
Then there isn't any problem.
@Ne0blast I think the trouble is at your side.
