### ISSUE TITLE
Right clic bug

### ISSUE THREAD

**Issue by ghost** [muonium/core#102]
When I'm clicking on the menu of the right clic, sometimes nothing happen (cf. clic on upload on the "..." part.

**Comment by Super-Baleine** [comment]
The function "move to" isn't coded yet.

**Comment by ghost** [comment]
When i'm clicking on "upload..." sometimes nothing happen

**Comment by Super-Baleine** [comment]
Okay, right now I just clicked 10 times on the "..." of "Upload a file", I didn't succeed to reproduce the bug.

**Comment by ghost** [comment]
Sorry, it was on "Create folder..." :)

![http://www.hostpic.org/images/1701071717590101.png](http://www.hostpic.org/images/1701071717590101.png)

**Comment by Super-Baleine** [comment]
Yea, sometimes it doesn't work, we know it.
We don't consider it as a bug because there are several improvements to do at the right click actions.
