### ISSUE TITLE
AES - Passphrase & ./proton

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#12]
We're using AES only with passphrase, not with private key.

So, we have to stock the passphrase like a password, and the proton folder is now useless. Because the proton folder was created to stocks private keys.

In fact, we have to consider the passphrase exactly as a password.

Hash it with sha512.

**Comment by Super-Baleine** [comment]
Look, this function is now obsolete : 
function uploadKeys() {

**Comment by dclement8** [comment]
Done.
