### ISSUE TITLE
Bug : Download doesn't work

### ISSUE THREAD

**Issue by ghost** [muonium/core#131]
Error when downloading file : 
Aborting 1  Files.js:42:4
File splitted in 1 chunks  Decryption.js:92:7
Decrypting chunk 1  Decryption.js:113:3
Got chunk 1 contents in 90 ms  Decryption.js:129:6
Key derivation process...  Decryption.js:143:7
Error
error { target: IDBOpenDBRequest, isTrusted: true, currentTarget: IDBOpenDBRequest, eventPhase: 2, bubbles: true, cancelable: true, defaultPrevented: false, composed: false, timeStamp: 1494253736298000, cancelBubble: false, originalTarget: IDBOpenDBRequest }  Decryption.js:19:3
UnknownError  idb.filesystem.min.js:15:250

**Comment by Super-Baleine** [comment]
@Ne0blast is the bug still up there?
ref. https://github.com/muonium/core/commit/490c6c39b54142182f42d888ec40ca0dbb981094

**Comment by ghost** [comment]
Still there :)

When i'm debugging the event, i'm getting this : "The operation failed for reasons unrelated to the database itself and not covered by any other error code." =>"UnknownError"

**Comment by Super-Baleine** [comment]
Well, can you give me more detail please?
- when it happens
- which script
- it's recursive (every time) or ponctual (somtimes)
- what's your web browser ? its release?
- if you're on chrom*, have you allowed Muonium to store data on your computer?

**Comment by ghost** [comment]
- When i attempt to download a file (always)
-  idb.filesystem.min.js:15:250
- Always
- Firefox 53.0.2 (last)

**Comment by Super-Baleine** [comment]
I'm running on Firefox 53.x too but I don't have this trouble. Perhaps you disabled something for the photon.muonium.ch domain name.

**Comment by Super-Baleine** [comment]
We got the bug, we're working on.

**Comment by ghost** [comment]
After debugging your script, it appears that there's a problem when SJCL is trying to derivate key.

In filename Decryption.js at line 137, you want to split a variable : `chk`. But ```split()``` is a function that only work on string and `chk` isn't a string, it's a `Uint8Array`. So when you're trying to do :
```javascript
var split = chk.split(":");
```

You got an error : `TypeError: chk.split is not a function` (when debugging) so you can't derivate the key using the parameters 
```javascript
var c = sjcl.codec.base64.toBits(split[0]);
var s = sjcl.codec.base64.toBits(split[1]);
var a = sjcl.codec.base64.toBits(split[2]);
var i = sjcl.codec.base64.toBits(split[3]);
```
I think split is considerate as an undefined variable so the rest of the code isn't properly executed :)

I don't know if it's really this, but that's the only thing i've seen.

**Comment by Super-Baleine** [comment]
Actually the bug appears because Firefox change some things in indexeDB in every release.

We know how to fix the bug, but the thing's that we don't have the time to work on it.

You can still use Muonium on Chromium, it works fine.

**Comment by ghost** [comment]
Okay, tested on edge and it works.

**Comment by Super-Baleine** [comment]
Edge is very low compared to Chrom*.

And using an encrypted service over a Microsoft product doesn't provide you any privacy.

**Comment by ghost** [comment]
I know, it was just for testing but it's the same on a google's product

**Comment by Super-Baleine** [comment]
Tested on Firefox 57, issue seems solved.

**Comment by ghost** [comment]
Tested on Firefox 56.0b6 (64-bit) : worked perfectly

**Comment by Super-Baleine** [comment]
Thanks for your feedback.

**Comment by ghost** [comment]
Np :)
