### ISSUE TITLE
Bug : dual authentication doesn't work

### ISSUE THREAD

**Issue by ghost** [muonium/core#132]
The mail isn't sended

**Comment by Super-Baleine** [comment]
hi, are you using Mui on your own server or on http://photon.muonium.ch?

**Comment by ghost** [comment]
Rectification, it is sended but after 5 minutes :) (on the Mui plateform)

**Comment by Super-Baleine** [comment]
Currently we've several Muonium servers, what server are you on? photon.muonium.ch?

**Comment by ghost** [comment]
https://photon.muonium.ch/neutron/Login

**Comment by Super-Baleine** [comment]
Well, I was just asking the domain name, thanks. We've the same issue on another server, I'm on.
