### ISSUE TITLE
Suggestion : Compress data in front-end before upload

### ISSUE THREAD

**Issue by ghost** [muonium/core#138]
I had a idea last night : You can compress the file data using https://github.com/LZMA-JS/LZMA-JS to reduce file size and encrypt it after that. 
When all the content is compressed and encrypted, you can upload it :)

**Comment by Super-Baleine** [comment]
We want to make Muonium as fast and light as possible.

Declined. Thanks anyway :)

**Comment by ghost** [comment]
Ok ;)

**Comment by ghost** [comment]
And through a back-end process ?

**Comment by Super-Baleine** [comment]
The goal isn't to make a software full of shitty implementations that would make it harder to maintain. 

We're focusing on lightness, speed, and security, not on compression, in this case. Moreover, it'd take too much load, at the front-end side, but also at the back-end side in the case we implement this at the server-side.
