### ISSUE TITLE
Feature : Multi-selection when CTRL is pressed

### ISSUE THREAD

**Issue by ghost** [muonium/core#140]
Don't know if it's already done or if you plan do to this :)

**Comment by Super-Baleine** [comment]
Please, create issue only for relevant stuffs. If you're not sure about something, don't open any issue, because it notifies us, hence we're quite distracted for actually nothing.

**Comment by Super-Baleine** [comment]
About multi-selection, we created a mode "multi-selection", feel free to enable it.
