### ISSUE TITLE
Suggestion : Use Paypal REST API instead of classic form

### ISSUE THREAD

**Issue by ghost** [muonium/core#145]
Isn't it better to use Paypal API to :
- Manage Paypal button ([https://developer.paypal.com/demo/checkout/#/](https://developer.paypal.com/demo/checkout/#/))
- Verify payment using the REST API ([https://developer.paypal.com/docs/api/payments/](https://developer.paypal.com/docs/api/payments/))

I think it's easiest to manage in the future and more secure (perhaps ?) :)

**Comment by Super-Baleine** [comment]
Hi,
Why do you think it'd be more secure?

**Comment by ghost** [comment]
When you use the form, you can edit it in local (input hidden) and send data to server. I think when you're using the API, it's directly managed by Paypal (without hidden input), so you can't send random values.

Plus, when you want to verify the payment, you just have to use the paymentID. If you want, i can send you by mail what i've done for CosmOS (using REST API).

**Comment by Super-Baleine** [comment]
@dclement8 might take a look at it.

**Comment by dclement8** [comment]
Hi, it's already secure but yes it's planned in the near future, it will be easier to manage in the long term.

**Comment by ghost** [comment]
Good to hear. If you want i've already done some scripts (server-side). I can send them to you :)

**Comment by Super-Baleine** [comment]
Hi,
The project is a free software. Feel free to contribute without asking. There's no point asking. Check the CONTRIBUTING.md file and get going if you wanna.

-------- Original Message --------

**Comment by ghost** [comment]
Yes but i've adapted it for my own application and i don't really think it'll fit your core system without modification. I paste it there so you don't have to search the file anywhere :)

**Comment by Super-Baleine** [comment]
Feel free to try implementing it if you wanna. We're currently working on something else, this is not a priority for us.

**Comment by dclement8** [comment]
I close this issue because we use currently CoinPayments API instead of PayPal API.
