### ISSUE TITLE
Suggestion : Shop in the user interface (future improvment)

### ISSUE THREAD

**Issue by ghost** [muonium/core#146]
Instead of just a storage upgrade choice, you can purpose a sort of shop with multi-choices upgrades or to switch to others plans (if the user can choose one of them). Plus, you can sell your shirts you've show in the indiegogo campain (Don't know if you've them in stock).

It's just a suggestion for the future of Mui, not realy for now :)

**Comment by Super-Baleine** [comment]
Hi,

In the future, we plan to propose several offers in addition to the current one.

For the tshirts, this is not related to the web application. We won't put a shop inside the web application itself.
