### ISSUE TITLE
Double auth

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#20]
- If the double auth is activated in the settings by the user then
  - send a code like this : "Miu-0565565"

The double auth is not activated by default.

In the register page, add a checkbox : 
**Do you want to active the double authentication ?**

We have to add a column in the table of the database for this.

**Comment by dclement8** [comment]
Double auth by sending an email with a code to the user ?

**Comment by Super-Baleine** [comment]
Yea

**Comment by dclement8** [comment]
Done

**Comment by Super-Baleine** [comment]
Did you test your code before pushing to 'master' ?

**Comment by dclement8** [comment]
Of course

**Comment by Super-Baleine** [comment]
"Of course", it's not very obvious XDD
Okay, fine :whale:
