### ISSUE TITLE
Clique droit

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#24]
This is the copy of the conversation between @hitoshi54 and me, and i'm too lazy to translate it, and we haven't any contributors, so, we do not care for the language of this issue.

**(Sur un fichier) (dans l'ordre) (FR - EN)**
- Télécharger - Download
- _(séparateur)_
- Favori - Star (donc mettre le fichier en favoris quoi, c'est comme un label en gros)
- _(séparateur)_
- Couper - Cut
- Copier - Copy
- Coller - Paste
- Supprimer - Delete
- _(séparateur)_
- Renommer... - Rename...
- Déplacer vers... - Move to...
- _(séparateur)_
- Voir les détails - View details

**(Sur un dossier) (idem) (idem)**
- Ouvrir - Open (donc entrer dans le dossier)
- _(séparateur)_
- Couper - Cut
- Copier - Copy
- Coller - Paste
- Supprimer - Delete
- _(séparateur)_
- Renommer... - Rename...
- Déplacer vers... - Move to...
- _(séparateur)_
- Voir les détails - View details

**(Dans le vide) (idem) (idem)**
- Nouveau dossier... - New folder..
- Charger des fichiers... - Upload files...
- _(séparateur)_
- Se déconnecter - Log out

**Comment by Super-Baleine** [comment]
@hitoshi54 j'ai update l'issue.
Bon, c'est la seule qu'on fait en FR, là j'avais juste grave la flemme de traduire x)

**Comment by Super-Baleine** [comment]
updated

**Comment by dclement8** [comment]
C'est fait ;)

**Comment by Super-Baleine** [comment]
Okay, i reopen because the actions are not coded yet.

**Comment by ghost** [comment]
you can add a new file when clicking nowhere

**Comment by Super-Baleine** [comment]
**"Charger des fichiers... - Upload files..."** in **"(Dans le vide) (idem) (idem)"**

**Comment by ghost** [comment]
i see it but you didn't have "Create a new file" on your actions' list

**Comment by Super-Baleine** [comment]
Oh, yea, nope. Because we work only with the end-to-end principle.
Okay, to change the passphrase, we will make an exception

**Comment by ghost** [comment]
You can create a new file with no content, in that case, the content of the new file is the AES encryption of a empty string no ?

**Comment by Super-Baleine** [comment]
Yea, but that's useless as fuck ^^

We'll implement the embedded webapps later, once implemented, you'll be able to create what you want.
