### ISSUE TITLE
Change text

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#28]
QC to Miu

**Comment by Super-Baleine** [comment]
@hitoshi54 while u code, check if you find "Quanta" and replace it by "Muonium" pls
And if a function is QC, you can change it to "Miu"

**Comment by Super-Baleine** [comment]
updated

**Comment by Super-Baleine** [comment]
I saw "var QuantaCloud" in Request.js in Interface/
In the view User.php, therefore you have : onclick quanta cloud blablabla

**Comment by dclement8** [comment]
Not used for now but I will change soon

**Comment by Super-Baleine** [comment]
K'ay

**Comment by Super-Baleine** [comment]
@hitoshi54 more of that, can you translate the french variable names in English please ?

**Comment by dclement8** [comment]
Done. Where are the french variable names ?

**Comment by Super-Baleine** [comment]
I saw some french variables there are some weeks ago, but maybe you corrected
