### ISSUE TITLE
Change passphrase - limits

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#31]
Avert the user that it can change its passphrase only 2 times per month.

**Comment by dclement8** [comment]
I added limitation but for now the user datum is not deleted (because user storage is not coded yet)

**Comment by Super-Baleine** [comment]
Okay

**Comment by Super-Baleine** [comment]
@hitoshi54 okay, so, we cannot recovery the passphrase if lost.
It was a mistake to code this temporary feature with the passphrase not hashed.

**Comment by Super-Baleine** [comment]
Hum, i think we have not to care about this issue for now.

**Comment by Super-Baleine** [comment]
Oups, mistake, sorry.
