### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#32]
**General**
- [x]  [esc] : hide the active content (like the "box" on the right click) - cancel
- [x] [CTRL+D] : disconnect
- [x]  [del(EN)/suppr (FR)] or [CTRL+T] : move to trash
- [x] CTRL+A : select all the files and folders
- [x] CTRL+R : move to trash
- [x] ARROWS : Navigate between files and folders
- [x] CTRL + C : Copy
- [x] CTRL + X : Cut
- [x] CTRL + V : Paste
- [x] ENTER : download the selected item, enter in the folder
- [x] CTRL+S : download the selected item(s)

- [x] RETURN <=> **cd ..**
 
**Note : this issue will be updated for a few moments. This note will be discarded when all the hotkeys will be assigned.**

**Comment by dclement8** [comment]
[CTRL+D] = add a favorite in Google Chrome, maybe [CTRL+L] is a better solution ?

**Comment by Super-Baleine** [comment]
Oh yea, that's true ! But, we cannot block this kind of shortcut ?

**Comment by ghost** [comment]
You can ! e.preventDefault(); with e the event in the onkeydown, onkeyup, onkeypress events

**Comment by Super-Baleine** [comment]
Yea, i saw this there is a few minutes ago x)

Thanks :heart:

**Comment by ghost** [comment]
But careful to not apply it directly in keypress events. If you do that, you'll be able to type anything. Be sure to use it when you detect CTRL + D or any keyboard shortcut you want to change.

**Comment by Super-Baleine** [comment]
@hitoshi54 
(my knight is the programmer, not me xD) (+1 for the nick name ?)

**Comment by dclement8** [comment]
@Ne0blast I tried with preventDefault(); and it works, thanks !

**Comment by Super-Baleine** [comment]
updated : CTRL+A

**Comment by dclement8** [comment]
@Super-Baleine I can't check "CTRL+A" checkbox x)

**Comment by Super-Baleine** [comment]
Okay, i did it.

That was because you weren't assigned i think.

**Comment by Super-Baleine** [comment]
I think we can close this issue, the main hotkeys are coded, nope ?

**Comment by Super-Baleine** [comment]
updated

**Comment by ghost** [comment]
If you want to use "applications" to view images, videos, edit text, etc... You must do a system to detect the focused application to use the hotkeys for the specified application and not hotkeys of the global interface ;)
For example, if you open an application, you can attribute a class "active" and then, when you detect a hotkey, you can test which application is focused and so active or not the shortcut.

Think about it :)

**Comment by Super-Baleine** [comment]
Hmmm, it's not planned to use applications. Because we have to do all of that in JavaScript, and we haven't any Js developer.

We are making general shortcuts, we will see later to implement some others web applications... It requires too much time, for now.

But thanks, we take this advice !

**Comment by ghost** [comment]
If you want, you can check this :
[https://github.com/Ne0blast/cosmos/blob/master/js/window.js](https://github.com/Ne0blast/cosmos/blob/master/js/window.js)

And this, if you want to create quickly applications (for the future) :
[https://github.com/Ne0blast/cosmos/tree/master/apps](https://github.com/Ne0blast/cosmos/tree/master/apps)

You can use my system and then develop it to your liking :)

**Comment by Super-Baleine** [comment]
Ahah xD Little vicious ! xD

Yea, you use the Apache V2 license, therefore we will perhaps implement some CosmOS app.

**Comment by ghost** [comment]
:D haha, it's just to help you.

Futhermore, i couldn't help you more with the work i've this year. I only develop the week-end (the sunday) but i really want you to succeed :)

**Comment by Super-Baleine** [comment]
Yea, thank you x)

I know, thanks ! x)

**Comment by ghost** [comment]
Perhaps, later, if i've more time, maybe i'll fork your project to help you again with the design (if you want). We'll see that in the future.

**Comment by Super-Baleine** [comment]
Oh, that could be cool !

**Comment by ghost** [comment]
A little addition for the shortcut :
- [ ] ESC : Unselect all elements
- [ ] ARROWS : Navigate between elements
- [ ] CTRL + clic : Select multiple elements
- [ ] CTRL + C : Copy
- [ ] CTRL + X : Cut
- [ ] CTRL + V : Paste
- [ ] ENTER : Open element or open directory (if an element is focused)
- [ ] CTRL + D : Download (proposition)
- [ ] CTRL + L : Logout (proposition)

Instead of CTRL + D" for disconnect, i would have put "CTRL + L" -> Logout and then "CTRL + D" to download an element.

**Comment by Super-Baleine** [comment]
CTRL + clic : Select multiple elements
done

**Comment by Super-Baleine** [comment]
updated

**Comment by Super-Baleine** [comment]
Answer to the edit for @Ne0blast : 
Nope, CTRL+D = Disconnect in MySQL, Shell/Bash/etc., and others things like that. CTRL+L is longer than CTRL+D.

**Comment by Super-Baleine** [comment]
@hitoshi54  Hmm, finally, we already have "del" to delete an item, therefore, we keep CTRL+R or not ?

**Comment by Super-Baleine** [comment]
updated

**Comment by ghost** [comment]
If you want to download a folder, you must zip it before

**Comment by Super-Baleine** [comment]
of course, but wait please xD 
We are coding a new "structure" for the files/folders managements... And we have many others features...

**Comment by Super-Baleine** [comment]
@Ne0blast if you have some shortcuts, tell us x)

**Comment by Super-Baleine** [comment]
updated : RETURN

**Comment by dclement8** [comment]
Done
