### ISSUE TITLE
Can't create worker with sjcl

### ISSUE THREAD

**Issue by ghost** [muonium/core#33]
SJCL use window.crypto which's not accessible in workers. You must change to another library to do that.

**Comment by Super-Baleine** [comment]
Currently, we use SJCL, but we'll see for openPGP.js, which normally supports AES, because it comply the openPGP "rules".

**Comment by Super-Baleine** [comment]
Please, also, check our uploading process #29 , we do not encrypt all the file, but the divided parts, called "modules".

We didn't test the process yet, we'll test it later.
