### ISSUE TITLE
Upload of a same file

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#35]
When uploading a file already existing on the current folder, replace the file by the new file being uploaded. Also update the database, don't create a new record.

check [here](https://github.com/muonium/core/issues/35#issuecomment-247677155)

**Comment by ghost** [comment]
I suggest you to not replace the file but to upload the with another name. For example :
- Current filename in a directory : filename.txt
- Uploaded file : filename_0.txt
  But do not replace or show a messageBox with a message like : "filename.txt already exists, do you want to replace it ? ". If not : rename it else do it ;)

It's just a suggestion :)

**Comment by Super-Baleine** [comment]
Yea, thanks, thats cool x)
It's just a post-it for Dylan, so, we haven't talk about it yet x)

**Comment by ghost** [comment]
k' ;)

**Comment by Super-Baleine** [comment]
We can also make it like MEGA.nz : upload the file, name it like the older file, and you make the difference with the last modification...

**Comment by ghost** [comment]
Or the id, with the database, you can do that but it's confusing to have files with the same name ;) i think.

**Comment by Super-Baleine** [comment]
You cannot see the id of the file with the webapp, it's the technical side ^^

But the last modification is shown x)

**Comment by ghost** [comment]
True :) But i still think that having 3 files with the same name is a bit confusing :)

**Comment by Super-Baleine** [comment]
Yea, i think so xD
But the user have to be a little intelligent by renaming before uploading, doesn't ?

But letting him the choice is the better solution indeed.

**Comment by ghost** [comment]
Or what you can if you detect that a name have already been take, show a messagebox with possibility to rename the file that'll be upload.

**Comment by Super-Baleine** [comment]
I agree with that solution, think thats the better

**Comment by ghost** [comment]
Talk to Dylan about that, i think he'll agree too :)

**Comment by Super-Baleine** [comment]
I linked him your comment about it.

**Comment by Super-Baleine** [comment]
I reopen with the idea, because this issue is done.
