### ISSUE TITLE
Implementation of SJCL

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#4]
*CEK : Content Encryption Key, this key encrypts the files 
*KEK : Key Encryption Key, this key encrypts the CEK

#Params: 
- key : 256 bits
- mode : GCM
- iteration : 2048 for files and 4096 for the CEK generation
- authentification data : random string, 128 bits

#Generation Process
- Generate a random key, let's call it "CEK" for "Content Encryption Key":

```javascript
var CEK  = sjcl.random.randomWords(8);
var CEK = sjcl.codec.base64.fromBits(CEK);
return CEK;
//output example : CDVOdrn+i+tAEu09Zhd+MX/TVIrSa76ZOBfUlRWck4U=
```

- KEK is just the passphrase of the user, this isn't a part of the generation process.

#Store Process
- Encrypt the CEK under the KEK:
```javascript
var CEK = "K5K2ak3bJXIy7GninEPodnKtVa9y2q5HOiLUPlvffX8="
var password = "the user's passphrase there !"
var aDATA  = sjcl.random.randomWords(3)
var aDATA  = sjcl.codec.base64.fromBits(aDATA)
var encryptedCEK = sjcl.encrypt(password, CEK,
{mode:'gcm', ks:256, ts:128, adata:aDATA, iter:2048})
var encryptedCEK = base64.encode(encryptedCEK)
//output example : eyJpdiI6ImZQMG9BUFhMbVRNYnNOMkJGbUk0MEE9PSIsInYiOjEsIml0ZXIiOjIwNDgsImtzIjoyNTYsInRzIjoxMjgsIm1vZGUiOiJnY20iLCJhZGF0YSI6IlUyOXZMMVF2ZVZkbVNuaGpSbkJHU1E9PSIsImNpcGhlciI6ImFlcyIsInNhbHQiOiIyYnBiTmRPYm00RT0iLCJjdCI6Ik9hMWhHY3dzU1hXaG4zUmh6Ums3RFVYS203TWNIdXYwU09zQlBPZW42c1BwOE82VzUrNWJhSGRRVWdZa0RKY2E5S0xBMC9qODNjRG5QSXJKIn0
```

- Store the encrypted CEK in the database

#Encryption & Decryption process
- Decrypt the CEK under the KEK:
```javascript
var CEK = base64.decode(encryptedCEK)
var CEK = sjcl.decrypt(password, CEK)
```

- Use the CEK as the passphrase to encrypt the files
```javascript
var CEK = "K5K2ak3bJXIy7GninEPodnKtVa9y2q5HOiLUPlvffX8="
var aDATA  = sjcl.random.randomWords(1)
var aDATA  = sjcl.codec.base64.fromBits(aDATA)
var cipheredFile = sjcl.encrypt(CEK, file, {
mode:'gcm', iter:2048, ks:256, ts:128, adata:aDATA})
```

**Comment by Super-Baleine** [comment]
Check this issue for more informations #29

**Comment by Super-Baleine** [comment]
Updated with little examples.

**Comment by Super-Baleine** [comment]
@TODO for @muonium/core_developers:

- $_t->AddJs my js implementation in the views, the js scripts are located at public/js/src/crypto/implementation
- Encrypt & Decrypt the file with crypt_files.js
- Decrypt and store in a cookie the CEK with crypt_cek.js

May this is be able to help you:

![sjclimplementation](https://cloud.githubusercontent.com/assets/13090164/20680237/7b4f397e-b59e-11e6-96a9-4cb77cacad53.png)
You have to make a conversion with bitArray etc etc... Before encrypt.

**Comment by Super-Baleine** [comment]
Process:
![diagramme1](https://cloud.githubusercontent.com/assets/13090164/20680548/c28994dc-b59f-11e6-869a-ade6944e9753.png)

**NOTE : CEK is decrypted by the user's passphrase, but the files are encrypted/decrypted by the decrypted CEK**

**Comment by Super-Baleine** [comment]
@hitoshi54 can we close now ?

**Comment by Super-Baleine** [comment]
The SJCL implement was made differently, checkout our crypto-system in public/js/interface/modules/Encryption.js

**Comment by dclement8** [comment]
Before closing this issue, what about the CEK in a cookie ?

**Comment by Super-Baleine** [comment]
The passphrase (alias "KEK) and the CEK must be stored locally.

Then cookie or localStorage, what's the more secure solution ?

**Comment by ghost** [comment]
[http://stackoverflow.com/questions/3220660/local-storage-vs-cookies#3220802](http://stackoverflow.com/questions/3220660/local-storage-vs-cookies#3220802)

**Comment by Super-Baleine** [comment]
Oh yea, what a dick... (We can see there that I'm not a coder)
Then @hitoshi54 we'll use sessionStorage.

**Comment by Super-Baleine** [comment]
btw, thanks @Ne0blast 💟

**Comment by Super-Baleine** [comment]
#71 go there now.

**Comment by Super-Baleine** [comment]
Oops, the CEK encryption isn't done, I reopen :)
