### ISSUE TITLE
Problem to download

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#40]
I cannot download .hex and others.
- Perhaps it's the mime type fault

**Comment by ghost** [comment]
You can test :
`header("Content-Type: application/octet-stream");` instead of `header("Content-Type: application/force-download");`

`header("Content-Type: application/force-download");` is a hack that must be avoided ;)

**Comment by Super-Baleine** [comment]
Yea, look at the last commit :)
This issue have to be closed...
@hitoshi54 think to close the issues, look... xD

**Comment by ghost** [comment]
My bad :D

**Comment by Super-Baleine** [comment]
@hitoshi54 
UPDATE, i reopen because there is another problem of this kind : 

i created ./test_test/test-/ , i entered, put a file, all it's okay.
But i cannot download it, same problem.
![capture du 2016-10-02 11 33 49](https://cloud.githubusercontent.com/assets/13090164/19019800/f45d03f6-8893-11e6-8e67-9842e058e60d.png)

Also, same problem even if the folders are named just "test".
To resume, it works only at the ROOT, nothing else.

**Comment by Super-Baleine** [comment]
Solved, gg my love.

**Comment by Super-Baleine** [comment]
@hitoshi54 i'm so sorry to find again this shitty bug... :'(
Post-it : same as the precedent, but only on the ROOT.

**Comment by Super-Baleine** [comment]
Okay, the problem appeared again : i cannot download the files stored at the root.

**Comment by Super-Baleine** [comment]
@hitoshi54 gj :heart:
