### ISSUE TITLE
multiple copies of a same file

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#52]
toto.txt -copy-> toto.txt (Copy)

but toto.txt (Copy) -copy-> toto.txt (Copy) <-- the file cannot be removed.

The file is removed as a file, but not as an data in the db.

**Comment by Super-Baleine** [comment]
update

**Comment by dclement8** [comment]
Corrected.

**Comment by Super-Baleine** [comment]
gj my love :heart:
