### ISSUE TITLE
Question : library\MVC\Model.php

### ISSUE THREAD

**Issue by ghost** [muonium/core#55]
In the file library\MVC\Model.php, you declare $_sql as protected and static variable but you attempt to use dynamically with $this.

Isn't it better to use self:: instead of $this, particularly in the __construct function with :
`
self::$_sql = new \PDO('mysql:host='.conf\confDB::hostDefaut.';dbname='.conf\confDB::bddDefaut,conf\confDB::userDefaut,conf\confDB::passDefaut);
        self::$_sql->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
        self::$_sql->setAttribute(\PDO::ATTR_EMULATE_PREPARES, false);
`

or in getLastInsertedId(), __get() or __set()

**Comment by dclement8** [comment]
I updated, thanks ;)

**Comment by ghost** [comment]
Np :)
