### ISSUE TITLE
Brute force

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#6]
Implement a code which fight the brute force. Like : 
- too much clicks (a click = an action)
- too much requests to register/connect

In javascript and PHP : one on the client-side, the other on the server-side.

If the Js tell nothing, then, verify with the PHP.
If the Js tell something, block it and don't call the PHP.

**Comment by dclement8** [comment]
In the PHP side it's done.
I think it's not useful in Js because with Ajax we already get result from php addUser function (with implementation of AntiBruteforce class)

**Comment by Super-Baleine** [comment]
Okay, we'll see that later together.

**Comment by Super-Baleine** [comment]
Okay, done.
