### ISSUE TITLE
"View details"

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#60]
When the user do right click and "view details", he has to see:

That's not in the order
- Location
- Size
- Last modification
- Icon
- Name

**Comment by Super-Baleine** [comment]
Updated: issue's content + assignments

**Comment by Super-Baleine** [comment]
In fact it's already done.

**Comment by ghost** [comment]
A little suggestion : when you click on the location's file, it open the folder

**Comment by Super-Baleine** [comment]
thanks
