### ISSUE TITLE
Quick issue :: title of 'General'

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#61]
That isn't "Profile" but "Files" or something like that...

![capture du 2016-11-14 01 58 37](https://cloud.githubusercontent.com/assets/13090164/20250319/b1fc019c-aa0d-11e6-8c5a-48154140a4b9.png)

I propose to name the title like that : 

**Mui :: Location** where Location is "General", "Shared", etc.

**Comment by dclement8** [comment]
Done.
