### ISSUE TITLE
else on conditions

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#7]
I found many conditions without "else", therefore i think there's many possibilities to fork bomb the client and perhaps the server.

**Comment by ghost** [comment]
If there's just a if, that doesn't make the client or server more vulnerable.

Just that you don't catch if the "if" statement isn't fullfill

**Comment by Super-Baleine** [comment]
When i was testing a Js script, my CPU worked at 100%... And, if i didn't close my web browser, i would be fork bombed.
And yea, thanks for u advices :love_letter:

**Comment by ghost** [comment]
Which script ?

**Comment by Super-Baleine** [comment]
log_connect.js with firefox 46 at my high school

**Comment by Super-Baleine** [comment]
I'll close it, and open again if the problem come back.

**Comment by ghost** [comment]
You made a mistake using aeJs : 

``` javascript
// You're using
aeJs.actions.encrypt(passphrase)

// instead of
aeJs.actions.encrypt("password", passphrase, 256);
```

Read the readme for more informations

**Comment by Super-Baleine** [comment]
Perhaps... I'll retry again later.
Thanks :cupid:
