### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by Super-Baleine** [muonium/core#79]
Hey, we don't care about robots.txt, right? I think we can delete it... that's useless you know...

**on github i mean**

**Comment by ghost** [comment]
Do some researches before posting something like that... It's not useless like you say, it's for the SEO : 
[https://moz.com/learn/seo/robotstxt](https://moz.com/learn/seo/robotstxt)

**Comment by Super-Baleine** [comment]
On GitHub i mean.

**Comment by Super-Baleine** [comment]
updated @Ne0blast , thx

**Comment by ghost** [comment]
Ah sorry ;) If it's on GitHub, i've nothing to say ^^

**Comment by Super-Baleine** [comment]
No problem.
The relative questions to the "Muonium's SEO management" haven't their place there. There, that's only to code, not for SEO or infra' questions... You know what I mean x)

Consequently, this kind of questions is generally about GitHub, even if exceptions exist... 🐳

**Comment by Super-Baleine** [comment]
Nobody cares so... i close xD
