### ISSUE TITLE
Sketch proposition

### ISSUE THREAD

**Issue by ghost** [muonium/core#83]
I made a sketch of the Muonium index page. Does it interest you ?
![Screenshot](http://s23.postimg.org/3qczwrmyh/Snap_Crab_Muonium_Mozilla_Firefox_2016_12_19_12.png)

**Comment by Super-Baleine** [comment]
Hey,
That's really cool, thanks!
But @adlewic , our designer is already working on, if you want to contribute to the design, then please, open a new issue in the website repo.

PS : this issue isn't relative to the current repo', please, the repo of the website is [there](https://github.com/muonium/website)
