### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by ghost** [muonium/core#88]
Message in http://127.0.0.1:8080/core/Register : 
/core/public/js/src/crypto/implementation/gen_cek.js was not found on this server

-> ReferenceError: genCek is not defined (log_register.js:74:7)

Using latest version of master's branch

**Comment by Super-Baleine** [comment]
Yea, we're currently working on the #87 . That's normal :)

**Comment by ghost** [comment]
Ah okay

**Comment by Super-Baleine** [comment]
Yea x)
But don't worry, in a few weeks it'll be done, we're on x)

**Comment by ghost** [comment]
So you delay the release of the private beta ?

**Comment by Super-Baleine** [comment]
We'll try to go out the private beta on the December 31th, but stop asking that... The private beta will go out once we'll be ready.
