### ISSUE TITLE
Correction for the logo display in Register et Login pages

### ISSUE THREAD

**Issue by ghost** [muonium/core#89]
In : 
- public/css/Register/home_register.css
-> Replace "height: 13vh;" at line 41 by "height: 8vh;padding-left:1vw;"

- public/css/Login/home_login.css
-> Same thing

![Screenshot](http://www.hostpic.org/images/1612232213040111.png)

**Comment by Super-Baleine** [comment]
#9

**Comment by Super-Baleine** [comment]
@adlewic I just assign you cuz you're the designer but that's just formal.

**Comment by Super-Baleine** [comment]
@Voxyd there is the solution, you're the only one who wanna fix that, then just do it boi 💟
