### ISSUE TITLE
display bug for the logo

### ISSUE THREAD

**Issue by dclement8** [muonium/core#9]
I added language selector in all views but now the logo is not centered.
Web browser : Google Chrome 50.0.2661.102 m (64-bit)
![issue1](https://cloud.githubusercontent.com/assets/19585678/15677711/be236ca2-274b-11e6-81cd-edbc6c1aca7f.PNG)

**Comment by Super-Baleine** [comment]
@BasilicApps and if you can write a css for the select language please...
Because in Firefox this is very ugly xD

**Comment by Super-Baleine** [comment]
updated: the assignees

**Comment by Super-Baleine** [comment]
updated assignees

**Comment by Super-Baleine** [comment]
Useless because Imelda is working on the new design.
I close then.
